### ISSUE TITLE
项目创建后保存数据的方法有问题

### ISSUE THREAD

**Issue by okzhangyu** [EDITeam/codegen#27]
1.此处的Recon是依据什么创建，项目中并没有创建这个类
<img width="569" alt="657447908127a318d2a932c5fd30816" src="https://user-images.githubusercontent.com/41094697/68377783-f7545a00-0185-11ea-86c4-b49f440b22e6.png">

2.这些飘红的对象也没有创建
<img width="480" alt="25bc0017ab9d3f415c2a8cf5d420a42" src="https://user-images.githubusercontent.com/41094697/68378065-6fbb1b00-0186-11ea-8341-5f103b7844ae.png">
3.调用存储过程的地方少了@Component注解
<img width="615" alt="7590f72b3ad7f9d139fc4a598a5c4bb" src="https://user-images.githubusercontent.com/41094697/68378172-9bd69c00-0186-11ea-8cb5-7d4eb940d417.png">

**Comment by fancys** [comment]
获取最新
