### ISSUE TITLE
showdoc生成文档问题

### ISSUE THREAD

**Issue by wangpenghuix** [EDITeam/codegen#57]
1.修改文档模版之后重新生成的文档不能覆盖以前的文档而是新增了一页
![image](https://user-images.githubusercontent.com/43561846/71350953-7a523800-25ad-11ea-9be5-de529144f46d.png)
![image](https://user-images.githubusercontent.com/43561846/71350965-83430980-25ad-11ea-8abd-38a39fa6a780.png)

**Comment by fancys** [comment]
title是目录，类似唯一键。catelog、title变更不会覆盖，而是新增
